package-lock.json, tsconfig.json
Signed-off-by: Claudiu Ion Lataretu <claudiu.lataretu@gmail.com>
=> Fix package includes for npm package

package-lock.json, package.json
=> Update module version to 0.0.3

package-lock.json, src/attributes-decoder/index.ts, src/attributes-decoder/locked-assets/index.ts, src/attributes-decoder/locked-assets/locked.asset.token.ts, src/attributes-decoder/locked-assets/locked.asset.token.types.ts, src/index.ts
=> Add locked asset attributes decoder

package-lock.json, src/attributes-decoder/index.ts, src/attributes-decoder/staking-proxy/dual.yield.token.ts, src/attributes-decoder/staking-proxy/dual.yield.token.types.ts, src/attributes-decoder/staking-proxy/index.ts, src/attributes-decoder/staking/index.ts, src/attributes-decoder/staking/staking.farm.token.ts, src/attributes-decoder/staking/staking.farm.token.types.ts, src/attributes-decoder/staking/unbond.farm.token.ts
=> Add staking tokens attributes decoders

package-lock.json, package.json
=> Bump version (0.0.4)

package-lock.json, src/event-decoder/metabonding/metabonding.event.ts
=> SERVICES-247 fix unbond event on empty data

package-lock.json, package.json
=> bump version to 0.0.6

package-lock.json, package.json
=> bump version to 0.0.7

package-lock.json, package.json
=> bump version to 0.0.8

.github/workflows/build.yml, .github/workflows/package-lock-checks.yml, package-lock.json
=> Add development branch for github actions

package-lock.json, package.json
=> Update erdjs version

package-lock.json, package.json
=> bump version to 0.0.9

package-lock.json, package.json
=> bump version to 0.1.0-alpha

package-lock.json, package.json
=> Bump version to 0.2.0-alpha

package-lock.json, package.json
=> Bump version to 0.2.1-alpha

package-lock.json, src/attributes-decoder/farm/farm.token.ts, src/attributes-decoder/farm/farm.token.types.ts, src/attributes-decoder/farm/farm.v1.3.token.ts, src/attributes-decoder/farm/farm.v2.token.ts
- create base attributes decoder; extend V1_3 from base
- add farm token V2 attributes decoder from base decoder
=> [SERVICES-846] refactor farm token attributes decoder

package-lock.json, package.json
=> bump version to 0.2.2-alpha

package-lock.json, src/event-decoder/weekly-rewards-splitting/claimMulti.event.ts, src/event-decoder/weekly-rewards-splitting/mocks/mocked.raw.event.ts
=> [SERVICES-953] fix decoded data for claimMulti event

package-lock.json, package.json
=> bump version to 0.2.8-alpha

.github/workflows/build.yml, .github/workflows/publish.yml, README.md, package-lock.json, package.json
=> [SERVICES-1158] change package name to sdk-exchange

package-lock.json, package.json, src/event-decoder/generic.types.ts, src/event-decoder/governance/governance.event.topics.ts, src/event-decoder/governance/governance.event.ts, src/event-decoder/governance/index.ts, src/event-decoder/governance/mocks/mocked.raw.event.ts, src/event-decoder/governance/specs/governance.event.spec.ts, src/event-decoder/index.ts
move vote event decoding implementation from microservice repo to sdk
=> MEX-364: vote event decoding implementation

package-lock.json, package.json, src/event-decoder/farm/specs/farm.event.v2.spec.ts, src/event-decoder/farm/v2/claim.rewards.event.ts, src/event-decoder/index.ts, src/event-decoder/staking/claim.rewards.event.ts, src/event-decoder/staking/index.ts, src/event-decoder/staking/mocks/mocked.raw.events.ts, src/event-decoder/staking/specs/staking.events.spec.ts, src/event-decoder/staking/stake.event.ts, src/event-decoder/staking/staking.event.topics.ts, src/event-decoder/staking/staking.types.ts, src/event-decoder/staking/unstake.event.ts
Added staking farm events decoders
=> [SERVICES-1884] staking farm events
